{{ config(materialized='table', schema='TEST') }}

WITH station_cte AS (
    SELECT
        ENDING_STATION_ID AS ENDING_STATION_ID,
        ENDING_STATION_LATITUDE AS ENDING_STATION_LATITUDE,
        ENDING_STATION_LONGITUDE AS ENDING_STATION_LONGITUDE,
        STARTING_STATION_ID AS STARTING_STATION_ID,
        STARTING_STATION_LATITUDE AS STARTING_STATION_LATITUDE,
        STARTING_STATION_LONGITUDE AS STARTING_STATION_LONGITUDE
    FROM "SPRINGBOARD"."TEST"."ROW_LOCATION"
)
SELECT * 
FROM station_cte

